import tkinter as tk
root = tk.Tk()
root.title("Registration Form")
full_Name_label = tk.Label(root,text = "Full name")
Full_Name_entry = tk.Entry(root)
email_label = tk.Label(root,text = "Email")
email_entry = tk.Entry(root)
Gender_label = tk.Label(root,text = "Gender")
male_ratio = tk.Radiobutton(root,text = "Male", value = "male")
female_ratio = tk.Radiobutton(root,text = "Female", value = "female")
country_label = tk.Label(root,text = "Country")
country_option = ["Select your country","USA","India","Canada","Mexico"]
country_var = tk.StringVar()
country_var.set(country_option[0])
countrydropdown = tk.OptionMenu(root,country_var,*country_option)
programming_label = tk.Label(root,text = "Programming")
java_check = tk.Checkbutton(root, text = "Java")
python_check = tk.Checkbutton(root, text = "Python")
Submit_button = tk.Button(root,text = "Submit",bg = "red", fg = "White")
full_Name_label.grid(row = 0, column = 0 )
Full_Name_entry.grid(row = 0, column = 1 )
email_label.grid(row = 1, column = 0 )
email_entry.grid(row = 1, column = 1 )
Gender_label.grid(row = 2, column = 0 )
male_ratio.grid(row = 2, column = 1)
female_ratio.grid(row = 2, column = 2 )
country_label.grid(row = 3, column = 0 )
countrydropdown.grid(row = 3, column = 1 )
programming_label.grid(row = 4, column = 0 )
java_check.grid(row = 4, column = 1 )
python_check.grid(row = 4, column = 2 )
Submit_button.grid(row = 5, column = 0 )
root.mainloop()
